### What are the differences between NumPy Lists and Python Lists?
Every element in a NumPy List is stored with no overhead. Each element is of the same size, and only the number or value is stored. In a Python List, on the other hand, every element that is stored has overhead, which includes (1) object value, (2) object type, (3) reference count, and (4) its size. This makes NumPy lists faster computationally and more efficient in terms of storage.

NumPy Lists have contiguous memory, while Python Lists have non - contiguous memory. A NumPy List of 8 elements, for example, is formed by 8 contiguous blocks of memory, each of the same size, where each block of memory stores the the element. A Python List of 8 elements, on the other hand, is formed by 8 blocks of memory, where each block of memory is just a reference to the actual element which can be anywhere in memory. Thus, in NumPy, the elements are stored in the list directly, while in Python, the references to the elements are stored.

<img src="numpy_list_information.png" alt="Drawing" style="width: 500px;"/>


### What are some characteristics of NumPy Lists?
- NumPy Lists have a fixed size. If the size of changed, what is really happening is the list is being recreated.
- NumPy Lists must store elements of all the same type, and thus, same size in memory.

In [2]:
import numpy as np



### Basics

In [4]:
# Creating NumPy Array
a = np.array([1, 2, 3])
print(a)

b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension
b.ndim

2

In [8]:
# Get Shape
print("Shape of a: " + str(a.shape))
print("Shape of b: " + str(b.shape))

Shape of a: (3,)
Shape of b: (2, 3)


In [10]:
# Get Type
print("Type of a: " + str(a.dtype))
print("Type of b: " + str(b.dtype))

Type of a: int64
Type of b: float64


In [12]:
# Get the size of the items in the NumPy array.
print(a.itemsize)
print(b.itemsize)

8
8


In [13]:
# Get the size (number of elements) of the NumPy array itself.
print(a.size)
print(b.size)

3
6


### Accessing / Changing Specific Elements, Rows, Columns, etc..

In [18]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

# Accessing Specific Elements
print(a[1, 2])

# Accessing a Specific Row
print(a[0, :])

# Acccessing a Specific Column
print(a[:, 2])

10
[1 2 3 4 5 6 7]
[ 3 10]


In [20]:
# We can also access elements from a NumPy list with a more interesting notation.
# [startindex:endindex:stepsize]

# The following code will first go to the 0th row, then get elements from index 1 to 6 
# such that there is a step size of 2 (so every other element is accessed and returned). 
a[0, 1:6:2]

array([2, 4, 6])

In [21]:
# Modifying Elements
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [22]:
# Modifying Sequences of Numbers at Once
a[0, ] = [-1, -2, -3, -4, -5, -6, -7]
print(a)

[[-1 -2 -3 -4 -5 -6 -7]
 [ 8  9 10 11 12 20 14]]


### Initializing Different Types of Arrays

In [26]:
# All Zero's Matrix
m1 = np.zeros((2, 3))
m2 = np.zeros((2, 3, 5))

print(m1)
print(m2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [27]:
# All One's Matrix
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [28]:
# Initialize a List with a Any Starting Number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [31]:
# Initialize a List with the same shape as an existing List. 
# Here, we initialize a NumPy List that has the starting value 
# 4 in each index and that has the same dimensions and size as m2.
np.full_like(m2, 4)

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [38]:
# Initialize a NumPy List with Random Decimal Number
np.random.rand(4, 2)

array([[0.26765641, 0.5338606 ],
       [0.78691867, 0.66103931],
       [0.81846804, 0.1087294 ],
       [0.38416242, 0.98140125]])

In [39]:
# Initialize a NumPy List with Random Interger Numbers
# In this case, we are creating a NumPy that is 3x3 and 
# that has elements with starting values from 0 to 7 overall.
# We have to pass in the size here explicitly and specify it.
np.random.randint(7, size=(3, 3))

array([[3, 1, 4],
       [5, 3, 1],
       [2, 5, 3]])

In [42]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
# Creating a List of Consecutive Numbers
# The NumPy function .arange() takes in one parameter and returns a one dimensional array 
# that goes from the number 0 until but not including the number passed in as the parameter. 
consecutive_numbers = np.arange(6)

print(consecutive_numbers)

# Reshaping a List
reshaped_consecutive_numbers = consecutive_numbers.reshape([2, 3])

print(reshaped_consecutive_numbers)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [62]:
# Repeat an Array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [66]:
# Coding Example (String Together Different NumPy Functions to Create an Array)
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be Careful When Copying Arrays!!!

In [76]:
# Let's create an array and try to make a copy of it.
a = np.array([1, 2, 3])
print("a: " + str(a))

b = a
print("b: " + str(b))

b[1] = 8

print("b modified: " + str(b))
print("a: " + str(a))

# Notice how we are not actually creating a copy of the NumPy Array / NumPy List a. 
# Instead, we are just creating a new reference b that points to the same NumPy List. 
# To make a deep copy, or a direct copy, we can use the following commands.
a = np.array([1, 2, 3])
b = a.copy()
b[1] = 8

print("\nProperly Creating a Copy of a NumPy List: ")
print("a: " + str(a))
print("b: " + str(b))

a: [1 2 3]
b: [1 2 3]
b modified: [1 8 3]
a: [1 8 3]

Properly Creating a Copy of a NumPy List: 
a: [1 2 3]
b: [1 8 3]


### What is axis in NumPy?
Source: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

Just like coordinate systems, NumPy arrays also have axes. For example, in a 2 - dimensional NumPy array, the axes are the directions along the rows and columns. We label these axes starting from axis 0 all the way up to axis (n - 1), where n is the number of dimensions of the NumPy List.

Let's look at a 2D array because it is most simple to understand axes in this dimension. Axis 0 is the axis that runs downward down the rows. Axis 1, on the other hand, is the axis that runs along the columns.

We can use NumPy axes in multiple different ways. When trying to understand axes in NumPy functions, we have to take a look at what the specific axis parameter in the function controls. We will have a look at a couple of different NumPy functions that have an axis parameter, and see how they work.

<img src="numpy_axis_1.png" alt="Drawing" style="width: 500px;"/>



In [67]:
# NumPy Sum with Axis
np_array_2d = np.arange(0, 6).reshape([2, 3])
print("Initial Array: ") 
print(str(np_array_2d) + "\n")

# Summing on Axis 0
m1 = np.sum(np_array_2d, axis = 0)
print("m1: " + str(m1))

# Summing on Axis 1
m2 = np.sum(np_array_2d, axis = 1)
print("m2: " + str(m2))


Initial Array: 
[[0 1 2]
 [3 4 5]]

m1: [3 5 7]
m2: [ 3 12]


In [68]:
# NumPy Concatenate with Axis
np_array_1s = np.array([[1, 1, 1], [1, 1, 1]])
np_array_9s = np.array([[9, 9, 9], [9, 9, 9]])

# Concatenates on axis 0, which is the axis running alongside rows. Thus, this will 
# double the number of rows in the resulting array. We concatenate along axis 0. 
concat1 = np.concatenate([np_array_1s, np_array_9s], axis = 0)

print("Concatenated Array 1: \n" + str(concat1))

# Concatenates on axis 1, which is the axis running alongside columns. Thus, this will 
# double the number of columsn in the resulting array. We concatenate along axis 1.
concat2 = np.concatenate([np_array_1s, np_array_9s], axis = 1)

print("Concatenated Array 2: \n" + str(concat2))

Concatenated Array 1: 
[[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]
Concatenated Array 2: 
[[1 1 1 9 9 9]
 [1 1 1 9 9 9]]


In [69]:
# Note that for 1 - D NumPy Lists, there is only one axis, called axis 0, that goes 
# along the columns. This is important to keep track of.

# Mathematics
We can do the following element - wise operations on NumPy Lists.

In [77]:
a = np.array([1, 2, 3, 4])

In [78]:
a + 2

array([3, 4, 5, 6])

In [79]:
a - 2

array([-1,  0,  1,  2])

In [80]:
a * 2

array([2, 4, 6, 8])

In [81]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [83]:
a += 2
print(a)

[5 6 7 8]


In [84]:
a ** 2

array([25, 36, 49, 64])

In [85]:
b = np.array([1, 0, 1, 0])
a + b

array([6, 6, 8, 8])

In [86]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

### Linear Algebra

In [91]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [92]:
# Matrix Multiplication
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [93]:
# Finding the Determinant (use the linalg package of NumPy)
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [94]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
# Finding the minimum values of a NumPy List
print(np.min(stats, axis = 0))
print(np.min(stats))

[1 2 3]
1


In [102]:
# Finding the maximum values of a NumPy List
print(np.max(stats))
print(np.max(stats, axis = 0))
print(np.max(stats, axis = 1))

6
[4 5 6]
[3 6]


In [103]:
# Finding the sum of a NumPy List
print(np.sum(stats))
print(np.sum(stats, axis = 0))
print(np.sum(stats, axis = 1))

21
[5 7 9]
[ 6 15]


### Reorganizing Arrays

In [105]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [106]:
# Vertically Stacking Vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
# Horizontal Stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Loading Data From File

In [116]:
# Here, we use the genfromtxt NumPy function to get data 
# from a text file. Then, we cast all the data from its 
# float type to an integer data type that takes up 32 
# bits. Finally, we display the variable by typing it.

filedata = np.genfromtxt("data.txt", delimiter = ",")
filedata.astype('int32')
filedata = filedata.astype('int32')

filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [119]:
# Returns true or false for every element, giving details 
# on whether it passes the condition given or if not.

filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [121]:
# We can use the true and false NumPy List to get all the 
# elements of the NumPy List filedata passing condition. 

# This also means we can index with a list in NumPy.

filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [123]:
# The any NumPy function allows the user to
# "test whether any array element along a given axis" 
# evaluates to True. Here, because we specified the axis 
# as 0, then, we are looking at each column in the data, 
# and for each column, we are seeing if any of the values 
# are greater than 50. If any of them are, a true is 
# placed in the return NumPy List at the index of the 
# column in the data.

np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [124]:
# The all NumPy function allows the user to
# "test whether all array elements along a given axis" 
# evaluate to True.

np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [125]:
# Specifying Multiple Conditions
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [126]:
# Specifying Multiple Conditions
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

##### More NumPy List Indexing

<img src="numpy_list_indexing.png" alt="Drawing" style="width: 500px;"/>